# Generated by Django 6.0.5 on 2026-08-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"]},
        ),
    ]
