# Generated by Django 6.0.5 on 2026-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="orders/receipts/"),
        ),
    ]
