# Generated by Django 6.0.5 on 2026-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
